version: 2
enable-beta-ecosystems: true

updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"

    - package-ecosystem: "cargo"
      directory: "/"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/crates/oxc"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/crates/oxc_allocator"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/crates/oxc_ast"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/crates/oxc_ast_macros"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/crates/oxc_cli"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/crates/oxc_codegen"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/crates/oxc_diagnostics"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/crates/oxc_index"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/crates/oxc_js_regex"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/crates/oxc_language_server"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/crates/oxc_linter"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/crates/oxc_macros"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/crates/oxc_minifier"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/crates/oxc_module_lexer"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/crates/oxc_parser"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/crates/oxc_prettier"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/crates/oxc_semantic"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/crates/oxc_sourcemap"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/crates/oxc_span"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/crates/oxc_syntax"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/crates/oxc_transformer"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/crates/oxc_traverse"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "npm"
      directory: "/crates/oxc_traverse/scripts"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "cargo"
      directory: "/crates/oxc_wasm"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "npm"
      directory: "/editors/vscode"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "cargo"
      directory: "/fuzz"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/napi/parser"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "npm"
      directory: "/napi/parser"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/npm/oxc-parser"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/npm/oxc"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/npm/oxlint"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "cargo"
      directory: "/tasks/benchmark"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "npm"
      directory: "/tasks/benchmark/codspeed"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "cargo"
      directory: "/tasks/common"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/tasks/coverage"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "npm"
      directory: "/tasks/coverage/Source/runtime"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "cargo"
      directory: "/tasks/javascript_globals"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "npm"
      directory: "/tasks/lint_rules"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "cargo"
      directory: "/tasks/minsize"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/tasks/prettier_conformance"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/tasks/rulegen"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/tasks/transform_conformance"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/wasm/parser"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "npm"
      directory: "/wasm/parser"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/website"
      schedule:
          interval: "daily"
      versioning-strategy: increase
